version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-rc-stretch
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.4
            bundle install
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
