version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@4.2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - ruby/install-deps
      # Store bundle cache
      - node/install-packages:
          pkg-manager: yarn
  test:
    parallelism: 4
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: rootpw
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Waiting for MySQL to be ready
            command: |
              for i in `seq 1 10`;
              do
                nc -z 127.0.0.1 3306 && echo Success && exit 0
                echo -n .
                sleep 1
              done
              echo Failed waiting for MySQL && exit 1
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
