version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@4.2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - ruby/install-deps
      # Store bundle cache
      - node/install-packages:
          pkg-manager: yarn
  test:
    parallelism: 4
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/mysql:8.0.3
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Waiting for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
