version: 2.1
orbs:
  ruby: circleci/ruby@1.1.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.4
            bundle install
  rspec:
    parallelism: 2
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - rails/yarn
      - rails/setup-database:
          schema-type: ruby
      - rails/test:
          test-runner: rspec
          coverage: true
          parallel: true
      - ruby/rubocop-check
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - rspec:
          requires:
            - build
