version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.4
            bundle install
      - ruby/bundle-install
  rspec:
    parallelism: 2
    executor: ruby/default
    steps:
      - checkout
      - rails/bundle:
          cache-version: "2"
          restore-only: true
      - rails/yarn:
          restore-only: true
      - rails/setup-database:
          schema-type: ruby
      - rails/test:
          test-runner: rspec
          coverage: true
          parallel: true
      - ruby/rubocop-check
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
